version: '3.4'

services:
  vaurien:
    build: 
      context: ./src/ResiliencePatternsDotNet.Httpbin/
    ports:
      - 9001:80
      - 9000:9000
    labels:
      traefik.enable: "true"
      traefik.vaurien.port: 80
      traefik.vaurien.frontend.rule: Host:vaurien.docker.localhost
      traefik.httpbin.port: 9000
      traefik.httpbin.frontend.rule: Host:httpbin.vaurien.docker.localhost

  resiliencepatternsdotnet.api:
    image: ${DOCKER_REGISTRY-}resiliencepatternsdotnetapi
    build:
      context: .
      dockerfile: src/ResiliencePatternsDotNet.Api/Dockerfile
    ports:
      - 5000:80
    depends_on: 
      - vaurien