version: '3.4'

services:
  resiliencepatternsdotnet.consoleapplication:
    image: ${DOCKER_REGISTRY-}resiliencepatternsdotnetconsoleapplication
    build:
      context: .
      dockerfile: ResiliencePatternsDotNet.ConsoleApplication/Dockerfile
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus
#    volumes:
#      - ./config:/prometheus
#      - ./data/prometheus:/data
#    command:
#      - '--config.file=/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/data'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - 9091:3000
    depends_on:
      - prometheus